version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "${KAFKA_SERVER:-kafka}"
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  # ui:
  #   image: obsidiandynamics/kafdrop
  #   container_name: kafka-ui
  #   environment:
  #     JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
  #     KAFKA_BROKERCONNECT: "157.90.228.89:9092"
  #   ports:
  #     - 9000:9000
  #   depends_on:
  #     - kafka
  #   tty: true

  producer:
    image: badrmoh/kafka-python-prod-demo:latest
    ports:
      - "${FLASK_PORT:-5000}:${FLASK_PORT:-5000}"
    environment:
      KAFKA_SERVER: "${KAFKA_SERVER:-kafka}"
      KAFKA_PORT: "${KAFKA_SERVER:-9092}"
      KAFKA_TOPIC: "${KAFKA_TOPIC:-test}"
      FLASK_HOST: "${FLASK_HOST:-0.0.0.0}"
      FLASK_PORT: "${FLASK_PORT:-5000}"
    tty: true
    stdin_open: true

  consumer:
    image: badrmoh/kafka-python-cons-demo:latest
    environment:
      KAFKA_SERVER: "${KAFKA_SERVER:-kafka}"
      KAFKA_PORT: "${KAFKA_SERVER:-9092}"
      KAFKA_TOPIC: "${KAFKA_TOPIC:-test}"
      PRODUCER_HOST: "${PRODUCER_HOST:-producer}"
      PRODUCER_PORT: "${FLASK_PORT:-5000}"
      PRODUCER_MSG_ENDPOINT: "${PRODUCER_MSG_ENDPOINT:-messages}"
    tty: true
    stdin_open: true

