apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cons-deployment
  labels:
    app: kafka-cons-deployment
  namespace: kafka-demo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-cons
      tag: python
  template:
    metadata:
      labels:
        app: kafka-cons
        tag: python
    spec:
      containers:
      - name: kafka-cons
        image: badrmoh/kafka-python-cons-demo
        envFrom:
          - configMapRef:
              name: kafka-cons-configmap