apiVersion: v1
data:
  KAFKA_ADVERTISED_HOST_NAME: "kafka-service"
  KAFKA_CREATE_TOPICS: "{{ .Values.kafka.config.topics }}"
  KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-service'
kind: ConfigMap
metadata:
  name: kafka-configmap
  namespace: {{ .Values.namespace.name }}