apiVersion: v1
data:
  KAFKA_SERVER: "kafka-service"
  KAFKA_PORT: "{{ .Values.kafka.service.port }}"
  KAFKA_TOPIC: "{{ .Values.prod.config.topic }}"
  FLASK_HOST: "0.0.0.0"
  FLASK_PORT: "{{ .Values.prod.service.port }}"
kind: ConfigMap
metadata:
  name: kafka-prod-configmap
  namespace: {{ .Values.namespace.name }}