apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cons-deployment
  labels:
    app: kafka-cons-deployment
  namespace: {{ .Values.namespace.name }}

spec:
  replicas: {{ .Values.cons.replicaCount }}
  selector:
    matchLabels:
      app: kafka-cons
      tag: python
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka-cons
        tag: python
    spec:
      containers:
      - name: kafka-cons
        image: {{ .Values.cons.image.name }}:{{ .Values.cons.image.tag }}
        envFrom:
          - configMapRef:
              name: kafka-cons-configmap
      nodeSelector:
{{ toYaml .Values.cons.nodeSelector | indent 8 }}
      tolerations:
{{ toYaml .Values.cons.tolerations | indent 8 }}