apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-service
  name: kafka-service
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.kafka.service.port }}
    protocol: TCP
    targetPort: {{ .Values.kafka.service.port }}
  selector:
    app: kafka
    tag: wurstmeister
  type: ClusterIP