apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-prod-service
  name: kafka-prod-service
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.prod.service.port }}
    protocol: TCP
    targetPort: {{ .Values.prod.service.port }}
  selector:
    app: kafka-prod
    tag: python
  type: ClusterIP