apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-prod-service
  name: kafka-prod-service
  namespace: kafka-demo
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: kafka-prod
    tag: python
  type: ClusterIP