apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  labels:
    app: zookeeper-deployment
  namespace: kafka-demo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
      tag: wurstmeister
  template:
    metadata:
      labels:
        app: zookeeper
        tag: wurstmeister
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper
        ports:
        - containerPort: 2181