name: Build/Push Docker Images
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yaml'
      - 'python/**'
      - '.github/workflows/docker.yml'
    workflow_dispatch:
jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    environment: 
          name: test
    steps:
      - uses: actions/checkout@v2
      
      # we need qemu and buildx so we can build multiple platforms later
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      # This makes image builds fast!      
      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  
      
      # this will build the images, once per platform, 
      # then push to both Docker Hub and GHCR
      - name: Build and push kafka producer image
        id: docker_build_producer
        uses: docker/build-push-action@v2
        with:
          context: python/kafka-prod
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          builder: ${{ steps.buildx.outputs.name }}
          # don't push during a pull_request, only build
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          
      - name: Show image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
      - name: Build and push kafka consumer image
        id: docker_build_consumer
        uses: docker/build-push-action@v2
        with:
          context: python/kafka-cons
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          builder: ${{ steps.buildx.outputs.name }}
          # don't push during a pull_request, only build
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
         
      - name: Show image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
